### ISSUE TITLE
help

### ISSUE THREAD

**Issue by GitGuy7** [Mist-Launcher/Beta-Bug-Reporting#1]
its says cmd error when i try to install the mods so i wanna see if you can help me
![image](https://github.com/Mist-Launcher/Beta-Bug-Reporting/assets/161498940/1bd72f26-634e-4922-9b75-e608f7c9f773)

**Comment by Ian502** [comment]
Same, I'm having the same issue, I tried adding mist as an exception to windows defender.

**Comment by Herwork06** [comment]
Sorry for the late response @GitGuy7 and @Ian502. Is this issue still occurring?
Since we thought we fixed it in patch 2

**Comment by GitGuy7** [comment]
> Sorry for the late response @GitGuy7 and @Ian502. Is this issue still occurring? Since we thought we fixed it in patch 2

Thank you it works

**Comment by Herwork06** [comment]
Nice!
