### ISSUE TITLE
500 Internal erro

### ISSUE THREAD

**Issue by TheBedrockEnder** [Mist-Launcher/Beta-Bug-Reporting#2]
Just says 500 internal error is stuck on launching mist downloaded from website, malwarebytes was closed 
![image](https://github.com/Mist-Launcher/Beta-Bug-Reporting/assets/113249084/f7dbc6c7-e53e-4606-85cf-f2cf40871a52)

**Comment by Herwork06** [comment]
Thank you for reporting!
We have received more reports about it and started looking for the issue this morning.

**Comment by Herwork06** [comment]
We found the issue. After reviewing, we found that one line of code was messing up the build code while the development side worked perfectly XD
New update should be out soon :D

**Comment by TheBedrockEnder** [comment]
will try reinstalling thx :)
